### ISSUE TITLE
Carriage return causing issues when tagging images

### ISSUE THREAD

**Issue by jsloan117** [treeder/bump#2]
> ./release.sh $SEMVER_LEVEL
> SEMVER_LEVEL="${1}"
> + SEMVER_LEVEL=patch
> 
> IMAGE_NAME=jsloan117/fluentd
> + IMAGE_NAME=jsloan117/fluentd
> IMAGE_TAG=dev
> + IMAGE_TAG=dev
> 
> if CURRENT_VERSION=$(docker run --rm "${IMAGE_NAME}":"${IMAGE_TAG}" cat VERSION 2> /dev/null); then
>   echo "${CURRENT_VERSION}" > VERSION
> fi
> ++ docker run --rm jsloan117/fluentd:dev cat VERSION
> + CURRENT_VERSION=0.0.1
> + echo 0.0.1
> 
> if [[ -n "${SEMVER}" ]]; then
>   echo "${SEMVER}" > VERSION
> fi
> + [[ -n 0.0.0 ]]
> + echo 0.0.0
> 
> NEXT_VERSION=$(docker run --rm -it -v "${PWD}":/app -w /app treeder/bump --filename VERSION "${SEMVER_LEVEL}")
> ++ docker run --rm -it -v /data/docker/fluentd:/app -w /app treeder/bump --filename VERSION patch
> + NEXT_VERSION=$'0.0.1\r'  <-- This is causing issues
> #NEXT_VERSION=$(echo "${NEXT_VERSION}" | sed -e 's/\r//') <-- Works fine removing the '\r'
> #NEXT_VERSION=$(cat VERSION) <-- Works fine assigning the variable here
> ##NEXT_VERSION=$(semver "$(cat VERSION)" -i "${SEMVER_LEVEL}")
> 
> ##echo $NEXT_VERSION > VERSION
> echo "version: ${NEXT_VERSION}"
> ' echo 'version: 0.0.1
> version: 0.0.1
> 
> # build container
> docker build -f Dockerfile -t "${IMAGE_NAME}":"${IMAGE_TAG}" .
> + docker build -f Dockerfile -t jsloan117/fluentd:dev .
> Sending build context to Docker daemon  10.75kB
> Step 1/4 : FROM fluent/fluentd:latest
>  ---> 9406ff63f205
> Step 2/4 : LABEL Name=fluentd maintainer="Jonathan Sloan"
>  ---> Using cache
>  ---> cfd87630467d
> Step 3/4 : RUN fluent-gem install fluent-plugin-elasticsearch
>  ---> Using cache
>  ---> 98a7f175dba8
> Step 4/4 : ADD VERSION .
>  ---> Using cache
>  ---> 965d13a439c3
> Successfully built 965d13a439c3
> Successfully tagged jsloan117/fluentd:dev
> 
> docker tag "${IMAGE_NAME}":"${IMAGE_TAG}" "${IMAGE_NAME}":"${NEXT_VERSION}"
> + docker tag jsloan117/fluentd:dev $'jsloan117/fluentd:0.0.1\r'
> Error parsing reference: "jsloan117/fluentd:0.0.1\r" is not a valid repository/tag: invalid reference format
> 
> rm -f VERSION
> + rm -f VERSION

As shown with multiple 'NEXT_VERSION' test strings, I'm able to get around this, but I thought I'd be able to use variable assignment correctly without having to use extra steps to get it to work.

**Comment by treeder** [comment]
I see what you're saying, should be an easy fix.

**Comment by treeder** [comment]
Fix is here: https://github.com/treeder/bump/pull/3

Wondering if this should be a flag option though, like `--raw` or something, since it makes regular output a bit harder to read (ie: if you're not using it like you are).

**Comment by jsloan117** [comment]
Very nice and thanks! I think it would be beneficial for a flag for people to have options. I wish I knew go... to assist...

**Comment by treeder** [comment]
Let me know if this works better for you now.

**Comment by jsloan117** [comment]
this works perfectly now! thanks again!!
