### ISSUE TITLE
major/minor versioning with gitbump.sh

### ISSUE THREAD

**Issue by brianrook** [treeder/bump#4]
I'm curious about the commit message trigger to increment major and minor version.  I've seen [pages that say it 'just works'](https://medium.com/@treeder/to-bump-major-or-minor-you-can-either-update-the-version-file-manually-and-reset-patch-to-zero-114a9d947c9e) with the commit message formatted the right way.  However, I can't get it to work. [ On closer inspection of the gitbump.sh](https://github.com/treeder/bump/blob/master/gitbump.sh) it looks like its hardcoded to 'patch'.

There's documentation further down that shows how to use the command to get the trigger from the message.  Does this mean that I would have to replicate the logic in gitbump.sh into a different set of commands in (for example) my github actions?  Is there a different script that I would use to get the trigger from the commit message?

**Comment by treeder** [comment]
That comment was from 3 years ago, so may have changed since then. I think the easiest is to do manual major/minor updates (which is probably good practice anyways), then just let this do the patch updates on every commit.

**Comment by brianrook** [comment]
cool.  thanks for getting back to me.  appreciated.
