### ISSUE TITLE
[feature request] label - build number arguments

### ISSUE THREAD

**Issue by xacnio** [treeder/bump#6]
# Request
`--label` and `--build-number` optional arguments.

`--label`
**Default:** null -> If version has a label, don't touch.
Result: If its defined, change label or if its empty, remove.

`--build-number`
**Default:** null -> If version has a build number, remove it. (i preferred this, may be its can be like --label)
Result: If its defined, change build number or use the same build number.

# Details
**Label (optional)**
it can be multiple words. It can contains `A-Z` `a-z` `0-9` `.` `-`
```
10.2.3-DEV-SNAPSHOT -> -DEV-SNAPSHOT
1.0.0-alpha.0valid -> -alpha.0valid
```
Match Regex: `\-[a-zA-Z-.0-9]+(?<![-.])`
Check Regex: `^[a-zA-Z-.0-9]+(?<![-.])$`

**Build number (optional)**
it can be multiple words. It can contains `A-Z` `a-z` `0-9` `.` `-`
```
1.1.2-prerelease+meta -> +meta
2.0.0+build.1848 -> +build.1848
```
Match Regex: `\+[a-zA-Z-.0-9]+(?<![-.])`
Check Regex: `^[a-zA-Z-.0-9]+(?<![-.])$`

**Comment by treeder** [comment]
I'm not sure I get what the expected results would be, can you clarify with some examples what exactly these should do.

**Comment by der-ali** [comment]
Lot of Docker tags include compatibility aka. 1.2.0-alpine11

Currently, if we run `docker run --rm  docker.io/treeder/bump --input " 1.2.0-alpine11" patch`, this results in `1.2.1` cutting out the compatibility

**Comment by treeder** [comment]
I see. Got a PR ready that adds `--prerelease` and `--metadata`

**Comment by treeder** [comment]
Let me know if this works now.
